name: CI/CD Pipeline for Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  docker-build:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner with Ubuntu

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push the Docker Image using Buildx
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use  # Set up Docker Buildx if not already available
          docker buildx build --push -t vsd23tech/hello-world:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Pull the Docker Image from Docker Hub (to ensure the image is available locally)
      - name: Pull Docker Image
        run: |
          docker pull vsd23tech/hello-world:latest

      # Step 5: Run the Docker Container
      - name: Run Docker Container
        run: |
          docker run -d --name hello-world-container vsd23tech/hello-world:latest

      # Optional: Verify the container is running
      - name: Verify Docker Container
        run: |
          docker ps  # List running containers
