name: CI/CD Pipeline for Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  docker-build:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner with Ubuntu

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image using buildx
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use  # Set up Docker Buildx if not already available
          docker buildx build --push -t your-dockerhub-username/hello-world:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Optionally, you could add more jobs like deployment, testing, etc.
